name: "Deploy on github pages"

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm i
      - run: npm run lint
      - run: npm run test

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint_and_test

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"
    - run: npm i
    - uses: actions/configure-pages@v3
    - run: npm run build
    - uses: actions/upload-pages-artifact@v2
      with:
        path: ./dist/
    - name: "Deploy GH page"
      id: deployment
      uses: actions/deploy-pages@v1

